version: '3.7'

services:
  web:
    container_name: vuln-nginx
    image: nginx:1.10
    ports:
      - 1234:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d:cached
      - .:/var/www/html:cached

  app:
    container_name: vuln-app
    build:
      context: .
    volumes:
      - .:/var/www/html:cached
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  database:
    image: mysql:5.7
    ports:
      - 33061:3306
    container_name: vuln-database
    environment:
      - "MYSQL_USER=almostroot"
      - "MYSQL_PASSWORD=password123"
      - "MYSQL_DATABASE=vulnerable_app"
      - "MYSQL_ROOT_PASSWORD=password123"
